---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-csi-driver-sa
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-cluster-role
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mountpoint-s3-csi-node-binding
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
subjects:
  - kind: ServiceAccount
    name: s3-csi-driver-sa
roleRef:
  kind: ClusterRole
  name: s3-csi-driver-cluster-role
  apiGroup: rbac.authorization.k8s.io
