---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-csi-driver-sa
  labels:
    app.kubernetes.io/name: aws-s3-csi-driver
    app.kubernetes.io/managed-by: eksctl
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::081342720926:role/AmazonS3CSIDriverFullAccess # CHANGE THIS ARN