---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-csi-driver-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/component: csi-driver

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-cluster-role
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get"]
  - apiGroups: ["s3.csi.aws.com"]
    resources: ["mountpoints3podattachments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get"]
    
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mountpoint-s3-csi-node-binding
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
subjects:
  - kind: ServiceAccount
    name: s3-csi-driver-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: s3-csi-driver-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-node-mountpoint-pod-namespace-role
  namespace: mount-s3
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/component: csi-driver
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-node-mountpoint-pod-namespace-role-binding
  namespace: mount-s3
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/component: csi-driver
subjects:
  - kind: ServiceAccount
    name: s3-csi-driver-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: s3-csi-driver-node-mountpoint-pod-namespace-role
  apiGroup: rbac.authorization.k8s.io
