---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-csi-driver-controller-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/component: csi-driver

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-cluster-role
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/component: csi-driver
rules:
  - apiGroups: [""]
    resources:
      ["pods", "persistentvolumeclaims", "persistentvolumes", "serviceaccounts"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["s3.csi.aws.com"]
    resources: ["mountpoints3podattachments"]
    verbs: ["create", "delete", "update", "get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-cluster-role-binding
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/component: csi-driver
subjects:
  - kind: ServiceAccount
    name: s3-csi-driver-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: s3-csi-driver-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-role
  namespace: mount-s3
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/component: csi-driver
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "watch", "delete", "list", "update"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-role-binding
  namespace: mount-s3
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
    app.kubernetes.io/component: csi-driver
subjects:
  - kind: ServiceAccount
    name: s3-csi-driver-controller-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: s3-csi-driver-controller-role
  apiGroup: rbac.authorization.k8s.io
