version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "scality/object"
    commit-message:
      prefix: "pip"
      include: scope
    labels:
      - "dependencies"
