---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gomod-root-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gomod"
    directory: "/tests/e2e-kubernetes"
    schedule:
      interval: "weekly"
    groups:
      gomod-e2e-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
