# Changes here may need to be backported to the latest 2.x and 1.x release branches.
# Backport if AWS is removing support for an EKS version, or if we're actively choosing to support a new k8s version on
# an old release.
matrix:
  cluster-type: ["eksctl"]
  arch: ["x86", "arm"]
  family:
    [
      "AmazonLinux2023",
      "Bottlerocket",
      "Ubuntu2404",
    ]
  kubernetes-version:
    ["1.31.0", "1.32.1", "1.33.2", "1.34.1", "1.35.0", "1.36.1"]
  include:
    # Enable enforcing mode for SELinux in AL2023, it's easier to list it in "include"
    # field rather than trying to exclude all other variants.
    - family: "AmazonLinux2023"
      selinux-mode: "enforcing"
  exclude:
    # Ubuntu2404 is only supported on EKS >= 1.33.
    # See https://eksctl.io/usage/custom-ami-support/?h=ubuntu#setting-the-node-ami-family.
    - cluster-type: "eksctl"
      family: "Ubuntu2404"
      kubernetes-version: "1.31.0"
    - cluster-type: "eksctl"
      family: "Ubuntu2404"
      kubernetes-version: "1.32.1"
