matrix:
  cluster-type: ["eksctl"]
  arch: ["x86", "arm"]
  family:
    [
      "AmazonLinux2",
      "AmazonLinux2023",
      "Bottlerocket",
      "Ubuntu2204",
      "Ubuntu2404",
    ]
  kubernetes-version:
    ["1.28.13", "1.29.8", "1.30.4", "1.31.0", "1.32.1", "1.33.2", "1.34.1"]
  include:
    # Ubuntu2004 is only supported on EKS <= 1.29.
    # See https://eksctl.io/usage/custom-ami-support/?h=ubuntu#setting-the-node-ami-family.
    - cluster-type: "eksctl"
      arch: "x86"
      family: "Ubuntu2004"
      kubernetes-version: "1.28.13"
    - cluster-type: "eksctl"
      arch: "arm"
      family: "Ubuntu2004"
      kubernetes-version: "1.29.8"
    # Enable enforcing mode for SELinux in AL2023, it's easier to list it in "include"
    # field rather than trying to exclude all other variants.
    - family: "AmazonLinux2023"
      selinux-mode: "enforcing"
  exclude:
    - cluster-type: "eksctl"
      arch: "arm"
      family: "Bottlerocket"
    # AL2 is not supported by Kubernetes 1.33.
    - cluster-type: "eksctl"
      family: "AmazonLinux2"
      kubernetes-version: "1.33.2"
    # AL2 is not supported by Kubernetes 1.34.
    - cluster-type: "eksctl"
      family: "AmazonLinux2"
      kubernetes-version: "1.34.1"
    # Ubuntu2204 is only supported on EKS >= 1.29 && EKS < 1.33.
    # See https://eksctl.io/usage/custom-ami-support/?h=ubuntu#setting-the-node-ami-family.
    - cluster-type: "eksctl"
      family: "Ubuntu2204"
      kubernetes-version: "1.28.13"
    - cluster-type: "eksctl"
      family: "Ubuntu2204"
      kubernetes-version: "1.33.2"
    - cluster-type: "eksctl"
      family: "Ubuntu2204"
      kubernetes-version: "1.34.1"
    # Ubuntu2404 is only supported on EKS >= 1.31.
    # See https://eksctl.io/usage/custom-ami-support/?h=ubuntu#setting-the-node-ami-family.
    - cluster-type: "eksctl"
      family: "Ubuntu2404"
      kubernetes-version: "1.28.13"
    - cluster-type: "eksctl"
      family: "Ubuntu2404"
      kubernetes-version: "1.29.8"
    - cluster-type: "eksctl"
      family: "Ubuntu2404"
      kubernetes-version: "1.30.4"
