###############################################################################
# Scality S3 CSI Driver – Markdownlint ruleset
# Every rule reference: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
###############################################################################
default: true

# Headings
MD001: true                         # Require heading levels to increment by one (H2 must follow H1, etc.)
MD003: { style: atx }               # Enforce `#`-style (ATX) headings instead of underlines
MD041: { level: 1 }                 # First content line must be a single top‑level H1 for page title

# Lists
MD004: { style: dash }              # Use '-' as bullet char for unordered lists for consistency
MD007: { indent: 2 }                # Indent nested list items by exactly 2 spaces
MD029: { style: ordered }           # Ordered lists should use "1. 2. 3." not "1. 1. 1."

# Spacing / blank lines
MD009:
  br_spaces: 2                      # Permit two trailing spaces that indicate a Markdown hard‑break
  list_item_empty_lines: false      # Disallow blank lines inside list items
MD010: true                         # Reject hard tab characters to avoid mixed whitespace
MD012: { maximum: 2 }               # No more than two consecutive blank lines to keep files tidy

# Line length
MD013:
  line_length: 200                  # Soft wrap at 200 chars—reasonable for technical docs on Github Pages
  heading_line_length: 200
  code_blocks: false                # Do not wrap code blocks
  tables: false                     # Do not wrap tables

# Duplicate headings (text can repeat at different nest levels, but not as siblings)
MD024:
  siblings_only: true

# Heading punctuation—disallow headings ending with punctuation chars
MD026:
  punctuation: ".,;:!。，；：！?"     # Disallow ending a heading with punctuation like '.', ',', ';', etc. for cleaner titles

# Inline HTML whitelist—allow common elements used by MkDocs Material, block all others
MD033:
  allowed_elements:
    - br
    - kbd
    - details
    - summary
    - svg
    - pathh                         # Permit only safe inline HTML tags used in docs styling (<kbd>, <details>, <svg> etc.)

# Bare URLs should be wrapped in < > or markdown link
MD034: true

# Code blocks & emphasis styling
MD046: { style: fenced }            # Require triple‑backtick fences
MD048: { style: backtick }          # Use backticks (```) not tildes (~~~)
MD049: { style: consistent }        # Whatever emphasis marker (* or _) appears first must be used consistently
MD050: { style: asterisk }          # Use **asterisk** not __underscore__ for bold

# Other toggles
MD014: false   # Allow shell prompt '$' in fenced code blocks
MD018: false   # Permit a space after '#' in headings (GitHub style)
MD025: false   # Multiple H1s allowed (some autogenerated pages include several)
