codecov:
  notify:
    wait_for_ci: true
    after_n_builds: 1

comment:
  layout: newheader, reach, files, components, diff, flags # show component info in the PR comment
  hide_comment_details: true  # hide the comment details (e.g. coverage targets) in the PR comment

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 30%
        removed_code_behavior: adjust_base
    patch:
      default:
        target: 90%
        threshold: 10%

github_checks:
  annotations: true

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses: []
