site_name: "Scality S3 CSI Driver"
site_url: https://scality.github.io/mountpoint-s3-csi-driver
repo_url: https://github.com/scality/mountpoint-s3-csi-driver
edit_uri: edit/main/docs/            # ← branch that holds Markdown

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: custom/moon
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: custom/sun
        name: Switch to light mode
  custom_dir: docs/assets/
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - navigation.top

extra_css:
  - assets/css/custom.css

plugins:
  - search
  - mermaid2
  - awesome-pages

markdown_extensions:
  - admonition # Enables notes, warnings, etc. Usage: !!! note
  - pymdownx.details  # For collapsible sections. Usage: ::: details
  - tables # For tables. Usage: |
  - attr_list  # For adding attributes to markdown elements (e.g., for badges). Usage: [!badge text](url)
  - md_in_html # For markdown in HTML. Usage: <div markdown="1">
  - meta # For metadata. Usage: --- title: "My Page" author: "John Doe" date: 2021-01-01 ---
  - toc:
      permalink: true # Adds anchor links to headings. Usage: [Heading](#heading)
      toc_depth: 2    # Depth of headings to include in the table of contents
      title: "On This Page"
  - pymdownx.highlight:
      anchor_linenums: true      # Makes line numbers clickable with URL anchors
      line_spans: __span         # Enables line highlighting and selection
      pygments_lang_class: true  # Adds language class for better styling
      linenums: true             # Shows line numbers on code blocks
      pygments_style: monokai    # Style of code blocks
  - pymdownx.inlinehilite       # Enables inline code highlighting
  - pymdownx.snippets           # Enables code snippets inclusion
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_div_format

nav:
  - Home: README.md
  - Quick Start: quick-start.md
  - Installation: installation.md
  - Configuration:
      - Overview: configuration/index.md
      - Driver Configuration: configuration/driver-configuration.md
      - Volume Configuration: configuration/volume-configuration.md
      - Mount Options: configuration/mount-options.md
  - How-To Guides:
      - Static Provisioning: how-to/static-provisioning.md
      - Mount Multiple Buckets: how-to/multi-volume.md
      - Region Override: how-to/region-override.md
      - Permissions & Non-Root Access: how-to/permissions.md
  - Concepts:
      - Filesystem Semantics: concepts/filesystem-semantics.md
  - Reference:
      - Compatibility Matrix: reference/compatibility-matrix.md
  - Operations:
      - Troubleshooting: troubleshooting.md
      - Administrator and User Guide: admin-user-guide.md
  - Reference:
      - Minimal Helm Example: examples/minimal-helm.yaml
