apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-rwx-storage
provisioner: s3.csi.aws.com
parameters:
  bucketName: my-rwx-bucket
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-rwx-claim
spec:
  accessModes:
    - ReadWriteMany  # Explicitly requesting ReadWriteMany access mode
  resources:
    requests:
      storage: 1Gi
  storageClassName: s3-rwx-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-rwx-app
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: s3-volume
      mountPath: /data
  volumes:
  - name: s3-volume
    persistentVolumeClaim:
      claimName: s3-rwx-claim