apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-bucket-storage
provisioner: s3.csi.aws.com
parameters:
  bucketName: my-statefulset-bucket
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: s3-storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: s3-storage
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "s3-bucket-storage"
      resources:
        requests:
          storage: 1Gi