// Code generated by MockGen. DO NOT EDIT.
// Source: systemd.go

// Package mock_system is a generated GoMock package.
package mock_system

import (
	context "context"
	reflect "reflect"

	system "github.com/scality/mountpoint-s3-csi-driver/pkg/system"
	dbus "github.com/godbus/dbus/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockDbusConn is a mock of DbusConn interface.
type MockDbusConn struct {
	ctrl     *gomock.Controller
	recorder *MockDbusConnMockRecorder
}

// MockDbusConnMockRecorder is the mock recorder for MockDbusConn.
type MockDbusConnMockRecorder struct {
	mock *MockDbusConn
}

// NewMockDbusConn creates a new mock instance.
func NewMockDbusConn(ctrl *gomock.Controller) *MockDbusConn {
	mock := &MockDbusConn{ctrl: ctrl}
	mock.recorder = &MockDbusConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbusConn) EXPECT() *MockDbusConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDbusConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDbusConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDbusConn)(nil).Close))
}

// Object mocks base method.
func (m *MockDbusConn) Object(dest string, path dbus.ObjectPath) dbus.BusObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Object", dest, path)
	ret0, _ := ret[0].(dbus.BusObject)
	return ret0
}

// Object indicates an expected call of Object.
func (mr *MockDbusConnMockRecorder) Object(dest, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Object", reflect.TypeOf((*MockDbusConn)(nil).Object), dest, path)
}

// Signal mocks base method.
func (m *MockDbusConn) Signal(ch chan<- *dbus.Signal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Signal", ch)
}

// Signal indicates an expected call of Signal.
func (mr *MockDbusConnMockRecorder) Signal(ch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockDbusConn)(nil).Signal), ch)
}

// MockDbusObject is a mock of DbusObject interface.
type MockDbusObject struct {
	ctrl     *gomock.Controller
	recorder *MockDbusObjectMockRecorder
}

// MockDbusObjectMockRecorder is the mock recorder for MockDbusObject.
type MockDbusObjectMockRecorder struct {
	mock *MockDbusObject
}

// NewMockDbusObject creates a new mock instance.
func NewMockDbusObject(ctrl *gomock.Controller) *MockDbusObject {
	mock := &MockDbusObject{ctrl: ctrl}
	mock.recorder = &MockDbusObjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbusObject) EXPECT() *MockDbusObjectMockRecorder {
	return m.recorder
}

// Go mocks base method.
func (m *MockDbusObject) Go(method string, flags dbus.Flags, ch chan *dbus.Call, args ...interface{}) *dbus.Call {
	m.ctrl.T.Helper()
	varargs := []interface{}{method, flags, ch}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Go", varargs...)
	ret0, _ := ret[0].(*dbus.Call)
	return ret0
}

// Go indicates an expected call of Go.
func (mr *MockDbusObjectMockRecorder) Go(method, flags, ch interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{method, flags, ch}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Go", reflect.TypeOf((*MockDbusObject)(nil).Go), varargs...)
}

// MockSystemdConnection is a mock of SystemdConnection interface.
type MockSystemdConnection struct {
	ctrl     *gomock.Controller
	recorder *MockSystemdConnectionMockRecorder
}

// MockSystemdConnectionMockRecorder is the mock recorder for MockSystemdConnection.
type MockSystemdConnectionMockRecorder struct {
	mock *MockSystemdConnection
}

// NewMockSystemdConnection creates a new mock instance.
func NewMockSystemdConnection(ctrl *gomock.Controller) *MockSystemdConnection {
	mock := &MockSystemdConnection{ctrl: ctrl}
	mock.recorder = &MockSystemdConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemdConnection) EXPECT() *MockSystemdConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSystemdConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSystemdConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSystemdConnection)(nil).Close))
}

// ListUnits mocks base method.
func (m *MockSystemdConnection) ListUnits(ctx context.Context) ([]*system.Unit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnits", ctx)
	ret0, _ := ret[0].([]*system.Unit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnits indicates an expected call of ListUnits.
func (mr *MockSystemdConnectionMockRecorder) ListUnits(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnits", reflect.TypeOf((*MockSystemdConnection)(nil).ListUnits), ctx)
}

// Signal mocks base method.
func (m *MockSystemdConnection) Signal(ch chan<- *dbus.Signal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Signal", ch)
}

// Signal indicates an expected call of Signal.
func (mr *MockSystemdConnectionMockRecorder) Signal(ch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockSystemdConnection)(nil).Signal), ch)
}

// StartTransientUnit mocks base method.
func (m *MockSystemdConnection) StartTransientUnit(ctx context.Context, name, mode string, props []system.DbusProperty) (dbus.ObjectPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransientUnit", ctx, name, mode, props)
	ret0, _ := ret[0].(dbus.ObjectPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransientUnit indicates an expected call of StartTransientUnit.
func (mr *MockSystemdConnectionMockRecorder) StartTransientUnit(ctx, name, mode, props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransientUnit", reflect.TypeOf((*MockSystemdConnection)(nil).StartTransientUnit), ctx, name, mode, props)
}

// StopUnit mocks base method.
func (m *MockSystemdConnection) StopUnit(ctx context.Context, unitName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopUnit", ctx, unitName)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopUnit indicates an expected call of StopUnit.
func (mr *MockSystemdConnectionMockRecorder) StopUnit(ctx, unitName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopUnit", reflect.TypeOf((*MockSystemdConnection)(nil).StopUnit), ctx, unitName)
}
