//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v2beta

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountpointS3PodAttachment) DeepCopyInto(out *MountpointS3PodAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountpointS3PodAttachment.
func (in *MountpointS3PodAttachment) DeepCopy() *MountpointS3PodAttachment {
	if in == nil {
		return nil
	}
	out := new(MountpointS3PodAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MountpointS3PodAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountpointS3PodAttachmentList) DeepCopyInto(out *MountpointS3PodAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MountpointS3PodAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountpointS3PodAttachmentList.
func (in *MountpointS3PodAttachmentList) DeepCopy() *MountpointS3PodAttachmentList {
	if in == nil {
		return nil
	}
	out := new(MountpointS3PodAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MountpointS3PodAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountpointS3PodAttachmentSpec) DeepCopyInto(out *MountpointS3PodAttachmentSpec) {
	*out = *in
	if in.MountpointS3PodAttachments != nil {
		in, out := &in.MountpointS3PodAttachments, &out.MountpointS3PodAttachments
		*out = make(map[string][]WorkloadAttachment, len(*in))
		for key, val := range *in {
			var outVal []WorkloadAttachment
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]WorkloadAttachment, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountpointS3PodAttachmentSpec.
func (in *MountpointS3PodAttachmentSpec) DeepCopy() *MountpointS3PodAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(MountpointS3PodAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAttachment) DeepCopyInto(out *WorkloadAttachment) {
	*out = *in
	in.AttachmentTime.DeepCopyInto(&out.AttachmentTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAttachment.
func (in *WorkloadAttachment) DeepCopy() *WorkloadAttachment {
	if in == nil {
		return nil
	}
	out := new(WorkloadAttachment)
	in.DeepCopyInto(out)
	return out
}
