services:
  s3:
    profiles: ['s3']
    image: ghcr.io/scality/cloudserver:${CLOUDSERVER_TAG:-7.70.65}
    network_mode: host
    environment:
      S3_CONFIG_FILE: /conf/config.json
      S3VAULT: mem
    command: /bin/sh -c "yarn start > /logs/s3/s3.log 2>&1"
    volumes:
      - ./cloudserver-config.json:/conf/config.json:ro
      - ./logs/s3:/logs/s3
