apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: mount-s3-critical
value: 1000000000
preemptionPolicy: Never
globalDefault: false
description: >-
    Default priority class for Mountpoint Pods.
    It has the highest possible value for non-builtin PriorityClasses to ensure Mountpoint Pods get scheduled quickly and not evicted first in case of a resource pressure.
    It will not cause other Pods to be preempted.

{{ if .Values.experimental.reserveHeadroomForMountpointPods -}}

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: mount-s3-preempting-critical
value: 1000000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: >-
    Preempting priority class for Mountpoint Pods.
    It has the highest possible value for non-builtin PriorityClasses to ensure Mountpoint Pods get scheduled quickly and not evicted first in case of a resource pressure.

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: mount-s3-headroom
value: -1000
globalDefault: false
description: >-
    Default priority class for Headroom Pods.
    It has a negative priority to allow Mountpoint Pods to evict them.

{{- end }}

