{{- if .Values.node.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.node.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.node.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.node.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.node.serviceAccount.automountServiceAccountToken }}
{{- end }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-cluster-role
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"] # TODO: Remove once we stop supporting systemd mounts because in PodMounter we get IRSA Role ARN from MountpointS3PodAttachment
    verbs: ["get"]
  - apiGroups: ["s3.csi.aws.com"]
    resources: ["mountpoints3podattachments"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mountpoint-s3-csi-node-binding
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
subjects:
  - kind: ServiceAccount
    name: {{ .Values.node.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: s3-csi-driver-cluster-role
  apiGroup: rbac.authorization.k8s.io

{{- if .Values.experimental.podMounter }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-node-mountpoint-pod-namespace-role
  namespace: {{ .Values.mountpointPod.namespace }}
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-node-mountpoint-pod-namespace-role-binding
  namespace: {{ .Values.mountpointPod.namespace }}
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.node.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: s3-csi-driver-node-mountpoint-pod-namespace-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}

{{- end -}}
