name: Code Validation

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [precommit, lint, unit-test, csi-compliance-test, controller-integration-test, validate-helm]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Setup Helm
      uses: azure/setup-helm@v4.3.0

    - name: Set up Python and install pre-commit (for precommit test)
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: pip

    - name: Download lychee binary (for precommit test)
      if: matrix.test == 'precommit'
      run: |
        curl -L https://github.com/lycheeverse/lychee/releases/download/lychee-v0.18.1/lychee-x86_64-unknown-linux-gnu.tar.gz -o lychee.tar.gz
        tar -xzf lychee.tar.gz
        sudo mv lychee /usr/local/bin/lychee
        lychee --version

    - name: Install pre-commit
      run: pip install -r requirements.txt

    - name: Run ${{ matrix.test }}
      run: make ${{ matrix.test }}
      env:
        # Skip golangci-lint hooks in precommit test since we run them separately in the 'lint' job
        # This saves 4 mins of CI time
        SKIP: ${{ matrix.test == 'precommit' && 'golangci-lint,go-fmt-imports-fumpt' || '' }}

    - name: Run golangci-lint
      if: matrix.test == 'lint'
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1.6

    - name: Check Go formatting
      if: matrix.test == 'lint'
      run: |
        # Install formatting tools
        go install golang.org/x/tools/cmd/goimports@latest
        go install mvdan.cc/gofumpt@latest

        # Check gofmt (built into Go)
        if [ -n "$(gofmt -l .)" ]; then
          echo "❌ gofmt issues found:"
          gofmt -l .
          exit 1
        fi

        # Check goimports
        if [ -n "$(goimports -l .)" ]; then
          echo "❌ goimports issues found:"
          goimports -l .
          exit 1
        fi

        # Check gofumpt
        if [ -n "$(gofumpt -l .)" ]; then
          echo "❌ gofumpt issues found:"
          gofumpt -l .
          exit 1
        fi

        echo "✅ All formatting checks passed!"

    - name: Upload unit test coverage to Codecov
      if: matrix.test == 'unit-test'
      continue-on-error: true
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: scality/mountpoint-s3-csi-driver

    - name: Upload controller test results to Codecov
      if: matrix.test == 'controller-integration-test'
      continue-on-error: true
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./controller-integration-tests-results.xml
        flags: controller_integration_tests
        slug: scality/mountpoint-s3-csi-driver
