name: Code Quality Checks

on:
  push:
    branches:
      - '**'

jobs:
  code-quality-checks:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [precommit, lint]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Set up Python and install pre-commit (for precommit test)
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: pip

    - name: Install pre-commit
      run: pip install -r requirements.txt

    - name: Download tools (for precommit test)
      if: matrix.test == 'precommit'
      run: |
        curl -L https://github.com/lycheeverse/lychee/releases/download/lychee-v0.18.1/lychee-x86_64-unknown-linux-gnu.tar.gz -o lychee.tar.gz
        tar -xzf lychee.tar.gz
        sudo mv lychee /usr/local/bin/lychee
        lychee --version
        go install golang.org/x/tools/cmd/goimports@latest
        go install mvdan.cc/gofumpt@latest

    - name: Run ${{ matrix.test }}
      run: make ${{ matrix.test }}
      env:
        # Skip golangci-lint hooks in precommit test since we run them separately in the 'lint' job
        # This saves 4 mins of CI time
        SKIP: ${{ matrix.test == 'precommit' && 'golangci-lint' || '' }}

    - name: Run golangci-lint
      if: matrix.test == 'lint'
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1.6
