name: "E2E Tests (ROSA Untrusted)"

on:
  pull_request_target:

permissions:
  id-token: write
  contents: read

jobs:
  approval:
    name: Approval Gate
    environment: "approval-gate"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id }}
    steps:
      - name: Approval Gate
        run: |
          echo "Approved!"
  e2e:
    name: E2E Tests
    uses: ./.github/workflows/e2e-rosa-tests.yaml
    needs: approval
    with:
      environment: "rosa-untrusted"
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit