name: S3 Endpoint URL Validation

on:
    push:
      branches:
        - '**'

jobs:
  validate-endpoint-url:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/e2e-setup-common
        with:
          ref: ${{ github.ref }}

      # Test 1: Verify Helm chart fails without endpoint URL
      - name: Test Helm Chart Validation
        run: |
          echo "Testing Helm chart validation for S3 endpoint URL..."
          if helm install test-release ./charts/scality-mountpoint-s3-csi-driver --dry-run 2>&1 | grep -q "S3 endpoint URL .* must be provided"; then
            echo "✅ Helm validation working: Install failed without endpoint URL"
          else
            echo "❌ Test failed: Helm install did not fail when S3 endpoint URL was missing"
            exit 1
          fi

      # Test 2: Verify Helm chart succeeds with endpoint URL
      - name: Test Helm Chart Success with Endpoint URL
        run: |
          echo "Testing Helm chart installs with endpoint URL provided..."
          if helm install test-release ./charts/scality-mountpoint-s3-csi-driver \
              --set node.s3EndpointUrl=https://test-endpoint.example.com \
              --dry-run > /dev/null; then
            echo "✅ Helm validation working: Install succeeded with endpoint URL provided"
          else
            echo "❌ Test failed: Helm install failed despite providing endpoint URL"
            exit 1
          fi

      # Test 3: Compile and test the driver without endpoint URL
      - name: Build Driver
        run: make bin

      - name: Test Driver Fails Without Endpoint URL
        run: |
          echo "Testing driver startup validation..."
          unset AWS_ENDPOINT_URL
          export CSI_NODE_NAME=test-node
          if ./bin/scality-csi-driver --endpoint unix:///tmp/test.sock 2>&1 | grep -q "AWS_ENDPOINT_URL environment variable must be set"; then
            echo "✅ Driver validation working: Startup failed without endpoint URL"
          else
            echo "❌ Test failed: Driver started when AWS_ENDPOINT_URL was missing"
            exit 1
          fi
